name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /var/www/html/laravel-mbti
          git pull
          yarn
          composer update
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_DB_CONNECTION: mysql
        envkey_DB_HOST: ${{ secrets.DB_HOST }}
        envkey_DB_PORT: ${{ secrets.DB_PORT }}
        envkey_DB_DATABASE: ${{ secrets.DB_DATABASE }}
        envkey_DB_USERNAME: ${{ secrets.DB_USERNAME }}
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        directory: /var/www/html/laravel-mbti
        file_name: .env