name: Laravel Testing (PHP)

on: [pull_request]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: mbti
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Setup Database 
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE mbti;' -uroot -p123456
          mysql -e 'SHOW DATABASES;' -uroot -p123456
          mysql -uroot -p123456 mbti < mbti.sql

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist
        env:
          APP_ENV: testing

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Migrate PHP
        run: |
          php artisan migrate

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}

      - name: Run yarn
        run: yarn && yarn dev

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit
        env:
          APP_ENV: testing

      - name: Run test cases
        run: ./vendor/bin/codecept run acceptance --steps
        env:
          APP_ENV: testing

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: ./storage/logs
